Merge with main
noumanity/nous-static-web pull request #2
Opened 2022-04-02 01:53 UTC by hugobcerdaminaya

Merge with main, dark mode and desktop and tablet responsiveness

2022-04-04 04:03 UTC, jvtrudel requested changes

2022-04-04 04:03 UTC, jvtrudel commented on index.html
> +    <script src="https://cdn.tailwindcss.com"></script>
do we need both styles.css and cdn.tailwindcss

2022-04-05 06:26 UTC, hugobcerdaminaya commented on assets/css/styles.css
> +! tailwindcss v3.0.23 | MIT License | https://tailwindcss.com
the command that generates it is 
npx tailwindcss -i ./src/styles.css -o ./public/assets/css/styles.css --watch

in the src/styles.css file you have the following imports, to generate the styles.css file in the public folder

![Captura srcstyles](https://user-images.githubusercontent.com/92815003/161691713-d3b10846-17e4-4f6e-8572-860fb9cab3ad.JPG)

![Captura tailwind_config](https://user-images.githubusercontent.com/92815003/161691940-012365c9-5bcb-4fd8-b56c-cf84f03b88be.JPG)

2022-04-05 06:30 UTC, hugobcerdaminaya commented on index.html
> +    <script src="https://cdn.tailwindcss.com"></script>
The line where the cdn is called will be removed, only the call to the styles.css file will remain, the script line for bg-color-about is also removed.

These changes are in a commit that I will upload shortly.

![Captura index](https://user-images.githubusercontent.com/92815003/161692618-ae3e7b22-1cee-44a0-a33c-d403f1e4fd0c.JPG)

2022-04-05 06:35 UTC, hugobcerdaminaya commented on index.html
> -                    <img class="w-96" src="./assets/img/logo noumanity-white.png" alt="">
@samuelsads  I'm reviewing and I believe those files were generated on your computer, I saw that when I checked the ._index file

![Captura  _index](https://user-images.githubusercontent.com/92815003/161693222-e103caa9-ecfb-4368-942d-53fb9f779369.JPG)

2022-04-06 02:36 UTC, merged